In [17]:
import os
import pandas as pd  # data processing, CSV file I/O (e.g. pd.read_csv)
import re
import threading
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.parse import parse_qs, urlparse

from bs4 import BeautifulSoup
import requests
from tqdm import tqdm

In [18]:
# Gets all projects into a DataFrame using an automated blank search
SEARCH_URL = "https://abstracts.societyforscience.org/"
s = requests.Session()


def fetch_all_projects_html(session):
    landing = session.get(SEARCH_URL, timeout=60)
    landing.raise_for_status()

    soup = BeautifulSoup(landing.text, "html.parser")

    token_input = soup.find("input", attrs={"name": "__RequestVerificationToken"})
    if token_input is None or not token_input.get("value"):
        raise RuntimeError("Could not find __RequestVerificationToken on landing page")

    year_values = [
        x.get("value")
        for x in soup.select("input[name='SelectedIsefYears'][type='checkbox']")
        if x.get("value")
    ]

    payload = {
        "__RequestVerificationToken": token_input["value"],
        "KeywordOrPhrase": "",
        "FinalistLastName": "",
        "IsGetAllAbstracts": "True",
    }

    if "0" in year_values:
        payload["SelectedIsefYears"] = "0"
    elif year_values:
        payload["SelectedIsefYears"] = year_values

    response = session.post(SEARCH_URL, data=payload, timeout=180)
    response.raise_for_status()
    return response.text


html = fetch_all_projects_html(s)
Path("projects.html").write_text(html, encoding="utf-8")

page_soup = BeautifulSoup(html, "html.parser")
project_ids = []
for link in page_soup.select("a[href*='FullAbstract']"):
    href = link.get("href") or ""
    query = parse_qs(urlparse(href).query)
    pid = query.get("projectId") or query.get("ProjectId")
    if pid:
        project_ids.append(pid[0])

ids = pd.Series(project_ids, dtype="string").drop_duplicates().reset_index(drop=True)

print(f"There are {len(ids)} projects")

There are 16199 projects

In [19]:
awards = pd.read_html("projects.html")[0]

awards.drop(["Year", "Finalist Name(s)", "Category"], axis=1, inplace=True)
awards.head()

,Project Title,Fair Country,Fair State,Fair Province,Awards Won
0,Distribution and Patterns of Movement of the W...,United States of America,FL,NaN,Intel Foundation Cultural and Scientific Visit...
1,The Use of Quantitative PCR to Determine the I...,United States of America,MN,NaN,NaN
2,Evaluation of Physiological Conditions that In...,United States of America,AR,NaN,NaN
3,Autism in Fruit Flies II: Behavior of Drosophi...,United States of America,OH,NaN,NaN
4,Environmentally Induced Epigenetic Transgenera...,United States of America,OK,NaN,NaN

In [20]:
def split_awards(award):
    if award:
        return str(award).split("  ")  # Splits by double spaces
    return None


awards["Awards Won"] = awards["Awards Won"].apply(split_awards)

In [21]:
# Gets the abstract and additional project information from each page
MAX_WORKERS = min(32, max(4, (os.cpu_count() or 1) * 5))
_thread_local = threading.local()


def get_session():
    if not hasattr(_thread_local, "session"):
        session = requests.Session()
        adapter = requests.adapters.HTTPAdapter(
            pool_connections=MAX_WORKERS,
            pool_maxsize=MAX_WORKERS,
            max_retries=1,
        )
        session.mount("http://", adapter)
        session.mount("https://", adapter)
        _thread_local.session = session
    return _thread_local.session


def get_paper_data(id):
    try:
        session = get_session()
        root = "https://abstracts.societyforscience.org/Home/FullAbstract?projectId="
        response = session.get(root + str(id), timeout=60)
        response.raise_for_status()

        soup = BeautifulSoup(response.content, "html.parser")

        # Gets the div whose class is row
        col = soup.find("div", attrs={"class": "col-sm-12"})
        elements = col.findChildren()

        title = elements[0].text

        category = elements[4].text.split("Category:")[1]

        year = int(elements[7].text.split("Year:")[1])

        finalists = elements[10].text.replace("  ", "").replace("\n", "")
        schools = [x.split(")")[0] for x in finalists.split("(School: ")[1:]]
        schools = set(schools)  # Removes duplicates

        abstract = elements[14].text.replace("Abstract:", "")

        return {
            "id": id,
            "title": title,
            "category": category,
            "year": year,
            "schools": schools,
            "abstract": abstract,
        }
    except Exception as e:
        return {
            "id": id,
            "title": None,
            "category": None,
            "year": None,
            "schools": None,
            "abstract": None,
            "error": e,
        }


with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    records = list(
        tqdm(
            executor.map(get_paper_data, ids.tolist()),
            total=len(ids),
            desc="Fetching abstracts",
        )
    )

database = pd.DataFrame(records)

database.dropna(subset=["title"], inplace=True)
database.head()

Fetching abstracts:   0%|          | 0/16199 [00:00<?, ?it/s]/var/folders/m0/sl2yvpv551gcfbk3gdntf74r0000gn/T/ipykernel_34646/4137760715.py:31: DeprecationWarning: Call to deprecated method findChildren. (Replaced by find_all) -- Deprecated since version 3.0.0.
  elements = col.findChildren()
Fetching abstracts: 100%|██████████| 16199/16199 [01:32<00:00, 174.98it/s]

,id,title,category,year,schools,abstract
0,13327,Distribution and Patterns of Movement of the W...,Plant Sciences,2014,{},Because a previously identified male pheromone...
1,13493,The Use of Quantitative PCR to Determine the I...,Plant Sciences,2014,{},Danio rerio are tropical transgenic zebrafish ...
2,13649,Evaluation of Physiological Conditions that In...,Biomedical and Health Sciences,2014,{},The purpose of this experiment was to find out...
3,13712,Autism in Fruit Flies II: Behavior of Drosophi...,Plant Sciences,2014,{},The study of genetic variations that cause aut...
4,13269,Environmentally Induced Epigenetic Transgenera...,Plant Sciences,2014,{},Environmental factors have a significant impac...

In [22]:
print(f"Length Before:{len(database.index):10d}")
database = database.join(awards.set_index("Project Title"), on="title")
print(f"Length After: {len(database.index):10d}")
database.head()

Length Before:     16199
Length After:      16244

,id,title,category,year,schools,abstract,Fair Country,Fair State,Fair Province,Awards Won
0,13327,Distribution and Patterns of Movement of the W...,Plant Sciences,2014,{},Because a previously identified male pheromone...,United States of America,FL,NaN,[Intel Foundation Cultural and Scientific Visi...
1,13493,The Use of Quantitative PCR to Determine the I...,Plant Sciences,2014,{},Danio rerio are tropical transgenic zebrafish ...,United States of America,MN,NaN,[nan]
2,13649,Evaluation of Physiological Conditions that In...,Biomedical and Health Sciences,2014,{},The purpose of this experiment was to find out...,United States of America,AR,NaN,[nan]
3,13712,Autism in Fruit Flies II: Behavior of Drosophi...,Plant Sciences,2014,{},The study of genetic variations that cause aut...,United States of America,OH,NaN,[nan]
4,13269,Environmentally Induced Epigenetic Transgenera...,Plant Sciences,2014,{},Environmental factors have a significant impac...,United States of America,OK,NaN,[nan]

In [23]:
# Renames some columns
database.rename(
    columns={
        "Fair Country": "country",
        "Fair State": "State",
        "Fair Province": "Province",
        "Awards Won": "awards",
    },
    inplace=True,
)

In [24]:
# Saves the file to CSV
output_path = Path("./data/isef-database.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)
database.to_csv(output_path, index=False)

# Removes projects.html from the output
Path("projects.html").unlink(missing_ok=True)

print(f"Saved database to: {output_path.resolve()}")

Saved database to: /Users/wkaiser/Coding/all-isef-projects/data/isef-database.csv